name: Update YouTube Data

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.14.0"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: scripts

      - name: Run update YouTube script
        run: pnpm run update:youtube
        env:
          SECRET_YOUTUBE_API_KEY: ${{ secrets.SECRET_YOUTUBE_API_KEY }}
        working-directory: scripts

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update of YouTube data
