name: Update YouTube Data

on:
  # schedule:
  #   - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.14.0"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run update script
        run: pnpm run update:youtube
        env:
          SECRET_YOUTUBE_API_KEY: ${{ secrets.SECRET_YOUTUBE_API_KEY }}
